
include: web-ext-utils

stages:
  read-fs:
    options:
      ignore: |
        /resources/
        /artifacts/

  build-manifest:
    options:
      set:
        permissions:
          - storage
          - notifications
          - tabs
      delete:
        - browser_action
