
include: web-ext-utils

pipelines:
  browsers: [ firefox ]

stages:
  read-fs:
    options:
      ignore: |
        /resources/
      importMap:
        imports:
          'es6lib/': '/node_modules/es6lib/'

  build-manifest:
    options:
      set:
        permissions:
          - storage
          - notifications
          - tabs
        commands:
          globalFocusKey:
            description: 'Focus the TST Tab Search bar'
        web_accessible_resources: [ '*' ]
