
include: web-ext-utils

stages:
  read-fs:
    options:
      ignore: |
        /resources/

  build-manifest:
    options:
      set:
        permissions:
          - storage
          - notifications
          - tabs
        commands:
          globalFocusKey:
            description: 'Focus the TST Tab Search bar'
